--Empire case 1
insert into CASES(CASEID,ARMYPOINTS,OPPONENTRACE,OUTCOME,PLAYERRACE)
 values(1,2500,'Skaven','Defeat','The Empire');
---Units
insert into UNIT(ID,NAME,NUMBER,COST,MOVEMENT,WEAPONSKILL,BALLISTICSKILL,STRENGTH,TOUGHNESS,WOUNDS,INITIATIVE,ATTACK,LEADERSHIP,UNITTYPE,ARMYTYPE)
 values(1,'Arch Lector of Sigmar',1,125,'4','4','3','4','4','3','4','2','9','In','Lord');
insert into UNIT(ID,NAME,NUMBER,COST,MOVEMENT,WEAPONSKILL,BALLISTICSKILL,STRENGTH,TOUGHNESS,WOUNDS,INITIATIVE,ATTACK,LEADERSHIP,UNITTYPE,ARMYTYPE)
 values(2,'Gold Wizard Lord',1,175,'4','3','3','3','4','3','3','1','8','In','Lord');
--insert into UNIT(ID,NAME,NUMBER,COST,MOVEMENT,WEAPONSKILL,BALLISTICSKILL,STRENGTH,TOUGHNESS,WOUNDS,INITIATIVE,ATTACK,LEADERSHIP,UNITTYPE,ARMYTYPE)
-- values();
--insert into UNIT(ID,NAME,NUMBER,COST,MOVEMENT,WEAPONSKILL,BALLISTICSKILL,STRENGTH,TOUGHNESS,WOUNDS,INITIATIVE,ATTACK,LEADERSHIP,UNITTYPE,ARMYTYPE)
-- values();
--insert into UNIT(ID,NAME,NUMBER,COST,MOVEMENT,WEAPONSKILL,BALLISTICSKILL,STRENGTH,TOUGHNESS,WOUNDS,INITIATIVE,ATTACK,LEADERSHIP,UNITTYPE,ARMYTYPE)
-- values();
---Equipment
insert into EQUIPMENT(EQUIPMENTID,TYPE,COST,NAME)
 values(1,'Mace',60, 'The Mace Of Helsturm');
insert into EQUIPMENT(EQUIPMENTID,TYPE,COST,NAME)
 values(2,'Armour',15,'Armour of Fortune');
insert into EQUIPMENT(EQUIPMENTID,TYPE,COST,NAME)
 values(3,'Potion',10,'Potion of Speed');
insert into EQUIPMENT(EQUIPMENTID,TYPE,COST,NAME)
 values(4,'Upgrade',35,'Lvl 4');
insert into EQUIPMENT(EQUIPMENTID,TYPE,COST,NAME)
 values(5,'Item',20,'Rod Of Power');
insert into EQUIPMENT(EQUIPMENTID,TYPE,COST,NAME)
 values(6,'Item',10,'Opal Amulet');
---Assign equipment to Unit
insert into UNIT_EQUIPMENT values(1,1);
insert into UNIT_EQUIPMENT values(1,2);
insert into UNIT_EQUIPMENT values(1,3);
insert into UNIT_EQUIPMENT values(2,4);
insert into UNIT_EQUIPMENT values(2,5);
insert into UNIT_EQUIPMENT values(2,6);
--UtilityUnits
insert into UTILITYUNIT(ID,NAME,NUMBER,COST,MOVEMENT,WEAPONSKILL,BALLISTICSKILL,STRENGTH,TOUGHNESS,WOUNDS,INITIATIVE,ATTACK,LEADERSHIP,UNITTYPE)
 values(1,'Warhorse',1,25,'5','3','3','3','2','3','4','4','3','_na');
--Assign utilityunit to unit
insert into UNIT_UTILITY values(2,1);
---Assign unit to case
insert into CASE_UNITS values(1,1);
insert into CASE_UNITS values(1,2);

