INSERT INTO ARMIES(ID,PLAYER_RACE,ARMY_POINTS)VALUES(1,'Empire',2500);
INSERT INTO ARMY_UNIT(ID,ARMY_ID,UNIT_NAME,NUM_UNITS)VALUES(0,1,'Empire:Arch Lector Of Sigmar',1);
INSERT INTO ARMY_UNIT_UTILITY(ARMY_UNIT_ID,UTILITY_ID)VALUES(0,12);
INSERT INTO ARMY_UNIT(ID,ARMY_ID,UNIT_NAME,NUM_UNITS)VALUES(1,1,'Empire:Kurt Helborg',1);
INSERT INTO ARMY_UNIT_UTILITY(ARMY_UNIT_ID,UTILITY_ID)VALUES(1,26);
INSERT INTO ARMY_UNIT(ID,ARMY_ID,UNIT_NAME,NUM_UNITS)VALUES(2,1,'Empire:The Emperor Karl Franz',1);
INSERT INTO ARMY_UNIT_UTILITY(ARMY_UNIT_ID,UTILITY_ID)VALUES(2,2);
INSERT INTO ARMY_UNIT_EQUIPMENT(ARMY_UNIT_ID,EQUIPMENT_ID)VALUES(2,27);
