/*
 *  Copyright (C) 2011 Glenn Rune Strandbråten
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * EquipmentUtilUI.java
 *
 * Created on 25.apr.2011, 12:25:51
 */

package myrmidia.UI;

import java.awt.Dimension;
import myrmidia.UI.Resources.UnitModel;

/**
 *
 * @author Glenn Rune Strandbråten
 */
public class EquipmentUtilUI extends javax.swing.JFrame {

    /** Creates new form EquipmentUtilUI */
    public EquipmentUtilUI(UnitModel unitModel) {
        initComponents();
        setListSizes();
        setTitle(unitModel.getName());
        initializeLists(unitModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equipmentScroll = new javax.swing.JScrollPane();
        equipmentList = new javax.swing.JList();
        utilityScroll = new javax.swing.JScrollPane();
        utilityList = new javax.swing.JList();
        magicScroll = new javax.swing.JScrollPane();
        magicList = new javax.swing.JList();
        promotionScroll = new javax.swing.JScrollPane();
        promotionList = new javax.swing.JList();
        magicLabel = new javax.swing.JLabel();
        equipmentLabel = new javax.swing.JLabel();
        utilityLabel = new javax.swing.JLabel();
        applyButon = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        promotionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        equipmentList.setCellRenderer(new myrmidia.UI.Resources.CheckBoxListRenderer());
        equipmentScroll.setViewportView(equipmentList);

        utilityList.setCellRenderer(new myrmidia.UI.Resources.CheckBoxListRenderer());
        utilityScroll.setViewportView(utilityList);

        magicList.setCellRenderer(new myrmidia.UI.Resources.CheckBoxListRenderer());
        magicList.setPreferredSize(new java.awt.Dimension(80, 30));
        magicScroll.setViewportView(magicList);

        promotionList.setCellRenderer(new myrmidia.UI.Resources.CheckBoxListRenderer());
        promotionList.setMaximumSize(new java.awt.Dimension(80, 30));
        promotionList.setMinimumSize(new java.awt.Dimension(80, 30));
        promotionList.setPreferredSize(new java.awt.Dimension(80, 30));
        promotionScroll.setViewportView(promotionList);

        magicLabel.setText("Magic pile");

        equipmentLabel.setText("Unit equipment");

        utilityLabel.setText("Utility units");

        applyButon.setText("Apply");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        promotionLabel.setText("Promotion unit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(equipmentScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(equipmentLabel)
                    .addComponent(promotionLabel)
                    .addComponent(promotionScroll, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cancelButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(applyButon))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(magicLabel)
                            .addGap(93, 93, 93))
                        .addComponent(magicScroll, 0, 0, Short.MAX_VALUE)
                        .addComponent(utilityScroll, 0, 0, Short.MAX_VALUE))
                    .addComponent(utilityLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equipmentLabel)
                            .addComponent(utilityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equipmentScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(utilityScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(promotionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(promotionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(magicLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(magicScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(applyButon)
                            .addComponent(cancelButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquipmentUtilUI(new UnitModel("<placeholder>",-1)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButon;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel equipmentLabel;
    private javax.swing.JList equipmentList;
    private javax.swing.JScrollPane equipmentScroll;
    private javax.swing.JLabel magicLabel;
    private javax.swing.JList magicList;
    private javax.swing.JScrollPane magicScroll;
    private javax.swing.JLabel promotionLabel;
    private javax.swing.JList promotionList;
    private javax.swing.JScrollPane promotionScroll;
    private javax.swing.JLabel utilityLabel;
    private javax.swing.JList utilityList;
    private javax.swing.JScrollPane utilityScroll;
    // End of variables declaration//GEN-END:variables

    private void initializeLists(UnitModel unitModel) {
        equipmentList.setListData(unitModel.getEquipment());
        utilityList.setListData(unitModel.getUtility());
        promotionList.setListData(unitModel.getPromotion());
        magicList.setListData(unitModel.getMagic());
    }

    private void setListSizes() {
        Dimension dim = new Dimension(120, 100);
        equipmentScroll.setPreferredSize(dim);
        equipmentScroll.setMaximumSize(dim);
        equipmentScroll.setMinimumSize(dim);
        utilityScroll.setPreferredSize(dim);
        utilityScroll.setMaximumSize(dim);
        utilityScroll.setMinimumSize(dim);
        magicScroll.setPreferredSize(dim);
        magicScroll.setMaximumSize(dim);
        magicScroll.setMinimumSize(dim);
        promotionScroll.setPreferredSize(dim);
        promotionScroll.setMaximumSize(dim);
        promotionScroll.setMinimumSize(dim);
        pack();
    }
}