/*
 *  Copyright (C) 2011 Glenn Rune Strandbråten 
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * createUnitSQLUI.java
 *
 * Created on 14.feb.2011, 09:41:02
 */

package org.Warhammer.UI;

import org.Warhammer.Warhammer.Unit.armyType;
import org.Warhammer.Warhammer.Unit.unitType;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Glenn Rune Strandbråten
 */
public class createUnitSQLUI extends javax.swing.JFrame {

    private static final String insertUnit = "INSERT INTO UNIT(NAME,RACE,COST,MINUNITS,MOVEMENT,WEAPONSKILL,BALLISTICSKILL,STRENGTH,TOUGHNESS,WOUNDS,INITIATIVE,ATTACK,LEADERSHIP,UNITTYPE,ARMYTYPE) VALUES(";
    private ArrayList<String> sql;
    /** Creates new form createUnitSQLUI */
    public createUnitSQLUI() {
            initComponents();
            sql = new ArrayList<String>();
            raceBox.addItem("Select race");
            for (org.Warhammer.Warhammer.Case.Races race : org.Warhammer.Warhammer.Case.Races.values()) {
                raceBox.addItem(race);
            }
            table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            String[] model = new String[12];
            model[0] = "N/A";
            int pos = 1;
            for (org.Warhammer.Warhammer.Unit.unitType ut : unitType.values()) {
                if (ut == unitType._na) {
                    continue;
                }
                model[pos] = ut.toString();
                pos++;
            }

            table.getColumnModel().getColumn(12).setCellRenderer(new org.Warhammer.UI.Resources.WarhammerCheckBoxTableCellRenderer(model, 12));
            model = new String[6];
            model[0] = "N/A";
            pos = 1;
            for (org.Warhammer.Warhammer.Unit.armyType ut : armyType.values()) {
                model[pos] = ut.toString();
                pos++;
            }
            table.getColumnModel().getColumn(13).setCellRenderer(new org.Warhammer.UI.Resources.WarhammerCheckBoxTableCellRenderer(model, 13));
            org.Warhammer.Database.DatabaseManager dbm =
                    org.Warhammer.Database.DatabaseManager.getInstance();
            dbm.connectWithoutHibernate();
            addUnit.doClick();
            addUnit.setMnemonic('a');


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        raceBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addUnit = new javax.swing.JButton();
        generateSQL = new javax.swing.JButton();
        executeSQL = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        raceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raceBoxActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Cost", "Min number of units", "M", "WS", "BS", "S", "T", "W", "I", "A", "Ld", "UnitType", "ArmyType"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setRowHeight(20);
        jScrollPane1.setViewportView(table);

        addUnit.setText("Add unit");
        addUnit.setEnabled(false);
        addUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUnitActionPerformed(evt);
            }
        });

        generateSQL.setText("Generate sql file");
        generateSQL.setEnabled(false);
        generateSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateSQLActionPerformed(evt);
            }
        });

        executeSQL.setText("Execute sql");
        executeSQL.setEnabled(false);
        executeSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeSQLActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(raceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addUnit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateSQL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(executeSQL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUnit)
                    .addComponent(generateSQL)
                    .addComponent(executeSQL)
                    .addComponent(loadButton)
                    .addComponent(raceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUnitActionPerformed
        DefaultTableModel tm = (DefaultTableModel) table.getModel();
        tm.addRow(new Object[]{null,null,null,null,null,null,null,null,null,null,null,null,"N/A","N/A"});
        table.setCellSelectionEnabled(true);
        table.getSelectionModel().setSelectionInterval(table.getRowCount()-1, table.getRowCount()-1);
        table.getColumnModel().getSelectionModel().setSelectionInterval(0, 0);
        table.requestFocus();
    }//GEN-LAST:event_addUnitActionPerformed

    private void generateSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSQLActionPerformed
        parseSQLSFromTable();
        org.Warhammer.File.SQLFileWriter.writeRaceUnitSQLFile(raceBox.getSelectedItem().toString(), sql);
    }//GEN-LAST:event_generateSQLActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
    JFileChooser jfc = new JFileChooser(new java.io.File("src/org/Warhammer/Database/Resources/"));
    jfc.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(java.io.File f) {
                String name = f.getName();
                if(name.startsWith("race_units"))
                    return true;
                else
                    return false;
            }

            @Override
            public String getDescription() {
                return "units in race SQL file";
            }
        });
        int ret = jfc.showOpenDialog(this);
        if(ret==JFileChooser.APPROVE_OPTION){
            emptyTable();
            ArrayList<String> result = org.Warhammer.File.SQLFileParser.parseRaceUnitsSQL(jfc.getSelectedFile());
            populteTable(result);
        }

    }//GEN-LAST:event_loadButtonActionPerformed

    private void raceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raceBoxActionPerformed
        if(raceBox.getSelectedIndex()==0){
            addUnit.setEnabled(false);
            generateSQL.setEnabled(false);
            executeSQL.setEnabled(false);
        }
        else{
            addUnit.setEnabled(true);
            generateSQL.setEnabled(true);
            executeSQL.setEnabled(true);
        }
    }//GEN-LAST:event_raceBoxActionPerformed

    private void executeSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeSQLActionPerformed
        try {
            parseSQLSFromTable();
            org.Warhammer.Database.DatabaseManager dbm = org.Warhammer.Database.DatabaseManager.getInstance();
            for (String string : sql) {
                dbm.executeSQL(string, org.Warhammer.Database.DatabaseManager.UPDATE_QUERY);
            }
            dbm.commit();
        }
        catch (SQLException ex) {
            Logger.getLogger(createUnitSQLUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (NullPointerException ex) {
            Logger.getLogger(createUnitSQLUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_executeSQLActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        org.Warhammer.Database.DatabaseManager.getInstance().disconnectNoHibernate(false);
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createUnitSQLUI().setVisible(true);
            }
        });
    }
    private void parseSQLSFromTable(){
        int rows = table.getRowCount();
        sql.clear();
        for(int i = 0 ; i < rows ; i++){
            if(table.getValueAt(i, 0)==null)
                continue;
            if(table.getValueAt(i, 1)==null)
                continue;
            if(table.getValueAt(i, 2)==null)
                continue;
            if(table.getValueAt(i, 3)==null)
                continue;
            if(table.getValueAt(i, 4)==null)
                continue;
            if(table.getValueAt(i, 5)==null)
                continue;
            if(table.getValueAt(i,6)==null)
                continue;
            if(table.getValueAt(i, 7)==null)
                continue;
            if(table.getValueAt(i, 8)==null)
                continue;
            if(table.getValueAt(i, 9)==null)
                continue;
            if(table.getValueAt(i, 10)==null)
                continue;
            if(table.getValueAt(i, 11)==null)
                continue;
            if(table.getValueAt(i, 12)==null)
                continue;
            if(table.getValueAt(i, 13)==null)
                continue;
            String name = table.getValueAt(i, 0).toString();
            int cost = (Integer)table.getValueAt(i, 1);
            int num = (Integer) table.getValueAt(i,2);
            String m = table.getValueAt(i,3).toString();
            String ws = table.getValueAt(i,4).toString();
            String bs = table.getValueAt(i,5).toString();
            String s =  table.getValueAt(i,6).toString();
            String t = table.getValueAt(i,7).toString();
            String w = table.getValueAt(i,8).toString();
            String in = table.getValueAt(i,9).toString();
            String a = table.getValueAt(i,10).toString();
            String ld = table.getValueAt(i,11).toString();
            String ut = table.getValueAt(i,12).toString();
            if(ut.contentEquals("N/A"))
                ut="_na";
            String at = table.getValueAt(i,13).toString();
            if(at.contentEquals("N/A"))
                at="_na";
            String race = raceBox.getSelectedItem().toString();
            String stat = insertUnit+"'"+race+":"+name+"','"+race+"',"+cost+","+num+",'"+m+"','"+ws+"','"+bs+"','"+s+"','"+t+"','"+w+"','"+in+"','"+a+"','"+ld+"','"+ut+"','"+at+"')";
            sql.add(stat);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUnit;
    private javax.swing.JButton executeSQL;
    private javax.swing.JButton generateSQL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JComboBox raceBox;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void populteTable(ArrayList<String> result) {
        DefaultTableModel tm = (DefaultTableModel) table.getModel();
        String race="";
        for (String string : result) {
            String[] s = parseQuery(string);
            race = s[1];
            if(s[13].contentEquals("_na"))
                s[13] = "N/A";
            if(s[14].contentEquals("_na"))
                s[14] = "N/A";
            tm.addRow(new Object[]{s[0],Integer.parseInt(s[2]),Integer.parseInt(s[3]),s[4],s[5],s[6],s[7],s[8],s[9],s[10],s[11],s[12],s[13],s[14]});
        }
        for (int i = 0; i < raceBox.getItemCount() ; i++) {
            Object object = raceBox.getItemAt(i);
            String s = object.toString();
            if(s.equalsIgnoreCase(race)){
                raceBox.setSelectedItem(object);
                break;
            }
        }
    }
    private String[] parseQuery(String q){
        int idx = q.indexOf("VALUES");
        String insert = q.substring(idx+7,q.length()-2);
        String clean = insert.replaceAll("'", "");
        idx = clean.indexOf(":");
        String ret = clean.substring(idx+1);
        return ret.split(",");
    }

    private void emptyTable() {
        DefaultTableModel tm = (DefaultTableModel) table.getModel();
        for (int i = tm.getRowCount()-1; i > -1; i--) {
            tm.removeRow(i);

        }
    }
}
