INSERT INTO CASES(ID,ARMY_ID,OPPONENT_RACE,OUTCOME)VALUES(1,2,'Wood_Elves','Victory');
INSERT INTO CASES(ID,ARMY_ID,OPPONENT_RACE,OUTCOME)VALUES(2,1,'Bretonnia','Defeat');
INSERT INTO CASES(ID,ARMY_ID,OPPONENT_RACE,OUTCOME)VALUES(3,5,'Dwarfs','Defeat');
INSERT INTO CASES(ID,ARMY_ID,OPPONENT_RACE,OUTCOME)VALUES(4,3,'Daemons_of_Chaos','Defeat');
INSERT INTO CASES(ID,ARMY_ID,OPPONENT_RACE,OUTCOME)VALUES(5,4,'Warriors_of_Chaos','Defeat');
INSERT INTO CASES(ID,ARMY_ID,OPPONENT_RACE,OUTCOME)VALUES(6,3,'High_Elves','Victory');
INSERT INTO CASES(ID,ARMY_ID,OPPONENT_RACE,OUTCOME)VALUES(7,3,'Warriors_of_Chaos','Victory');
